version: '3.7'

services:
  db-mysql:
    container_name: db-mysql
    image: mysql:8
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - network-backend

networks:
  network-backend:
    driver: bridge
    name: network-backend
